### PR TITLE
Update project directory .xml and PMSspecs files.

### PR DESCRIPTION
**Pull request by tthomas88**
For PMSspecs files, reduce FIRST_BIN value by 1, minumum 0. Reduce LAST_BIN values by 1 if LAST_BIN == 31, 41, 100.

For .xml file, change length=31 to length=30 & length=100 to length=99

### CODE REVIEW

**Comment by tthomas88** [comment]
I received and email to my personal email address, which is why I missed your commend Catherine. I will updated my settings in GitHub. 

This issue that you note is something that Chris instructed me to do: only change the LAST_BIN value if it equals 31, 41, or 100. I can already see a few cases where I made an error: CONTRAST PMSSpecs line 194, 269. Apart from that, there will be many, many cases where the FIRST_BIN is reduced and the LAST_BIN is unchanged. Hopefully that addresses your question. Thanks.

**Comment by topher800** [comment]
The 260X, 2DC and 2DP probes have 64 diodes.  So in reality we should have
had 65 as the last bin, however....

  When doing entire-in algorithm.  If either edge diode is touched, then
the particle is rejected.  So in reality only 62 bins is used.

CLIMET and RDMA won't be flown or processed ever again. The FSS's you list
have not been flown in ADS3.  We can/will adjust if they come back...and
perhaps we should remove probes that have not been flown in a decade from
the Configuration/PMSspecs

**Comment by catdewey** [comment]
Thanks for the clarification on the LAST_BIN's. 
And the reminder about personal email: I also need to figure out my settings.

**Comment by tthomas88** [comment]
I am closing this pull request to fix a few LAST_BIN errors with CONTRAST PMSspecs and possibly other projects. I will issue another pull request once ready. I can remove probes from the configuration PMSspecs file, as appropriate. Thanks for the comments.

**Pull request closed without merging**
